name: alexrisa
favicon: null
layout_spectrum: 0.10667904303409159
typography_spectrum: 0.4834205585066229
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9783014310523868
  lightness: 0.6429607414174825
  saturation: 0.8306388275232166
  rhythmicContrast: 0.3896534873638302
purpose: []
